name: panelmekar
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: 1.0.6
  google_fonts: ^6.2.1
  http: 1.1.2
  intl: 0.18.1
  excel: 4.0.2
  path_provider: 2.1.2
  share_plus: ^7.2.2
  print_bluetooth_thermal: ^1.2.1
  esc_pos_utils_plus: ^2.0.4
  permission_handler: 10.4.5
  image_picker: 1.0.7
  url_launcher: 6.2.4
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 3.0.1
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/logomekar.svg
    - assets/images/logomekar.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logomekar.png"
  min_sdk_android: 21
  adaptive_icon_background: "#7F00FF"
  adaptive_icon_foreground: "assets/images/logomekar.png"